### ISSUE TITLE
dnf install kopia-ui 0.13.0-1 fails due to file conflicts with slack 4.32.122-0

### ISSUE THREAD

**Issue by burritts** [kopia/kopia#3054]
Output from dnf install follows.  It says files installed in folders like /usr/lib/.build-id/xx/someid conflict with an already installed slack package.  I wonder if these files need to be installed at all - perhaps both kopia-ui and slack have packaged them in error?  That's just a guess, I have no expertise in this area.

The install is from the yum repository setup according to: https://kopia.io/docs/installation/#linux-installation-using-rpm-redhat-centos-fedora, eg: baseurl=http://packages.kopia.io/rpm/stable/\$basearch/

```
sudo dnf install kopia kopia-ui
Last metadata expiration check: 0:57:06 ago on Fri 02 Jun 2023 12:12:50 PM.
resolving
Dependencies resolved.
======================================================================================================================================================
 Package                              Architecture                       Version                              Repository                         Size
======================================================================================================================================================
Installing:
 kopia                                x86_64                             0.13.0-1                             Kopia                              12 M
 kopia-ui                             x86_64                             0.13.0-1                             Kopia                              74 M

Transaction Summary
======================================================================================================================================================
Install  2 Packages

Total download size: 86 M
Installed size: 308 M
Is this ok [y/N]: y
Downloading Packages:
(1/2): kopia-0.13.0.x86_64.rpm                                                                                        586 kB/s |  12 MB     00:21    
(2/2): kopia-ui-0.13.0.x86_64.rpm                                                                                     823 kB/s |  74 MB     01:31    
------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                 959 kB/s |  86 MB     01:31     
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  file /usr/lib/.build-id/0d/26926182c322d82267af2501cc8b44df5fa139 from install of kopia-ui-0.13.0-1.x86_64 conflicts with file from package slack-4.32.122-0.1.el8.x86_64
  file /usr/lib/.build-id/44/8a07f59b13491266431a3ae922b2975406231d from install of kopia-ui-0.13.0-1.x86_64 conflicts with file from package slack-4.32.122-0.1.el8.x86_64
  file /usr/lib/.build-id/53/19d04906b8dc63f0d57ca901895daa22bc9e6f from install of kopia-ui-0.13.0-1.x86_64 conflicts with file from package slack-4.32.122-0.1.el8.x86_64
  file /usr/lib/.build-id/71/e167daae4e18dbd6162a7293c04fc99e7ca1aa from install of kopia-ui-0.13.0-1.x86_64 conflicts with file from package slack-4.32.122-0.1.el8.x86_64
  file /usr/lib/.build-id/a0/5fa5879372db74e11a96eab790863c25271949 from install of kopia-ui-0.13.0-1.x86_64 conflicts with file from package slack-4.32.122-0.1.el8.x86_64
  file /usr/lib/.build-id/b7/fc1a44ebdfd56bdb264d9027d2b3de4ed20436 from install of kopia-ui-0.13.0-1.x86_64 conflicts with file from package slack-4.32.122-0.1.el8.x86_64
  file /usr/lib/.build-id/d6/e4f7b4e0e9b3f8f6c1c4ac372e4c32e5afe5df from install of kopia-ui-0.13.0-1.x86_64 conflicts with file from package slack-4.32.122-0.1.el8.x86_64
  file /usr/lib/.build-id/f8/d73cc14ed682ca59c2beeeac3ac79f59a3d016 from install of kopia-ui-0.13.0-1.x86_64 conflicts with file from package slack-4.32.122-0.1.el8.x86_64
`
```

**Comment by OperKH** [comment]
Have the same issue.

**Comment by lupusA** [comment]
Hi @burritts,

Is it solved with version 0.14.1?

Cheers

**Comment by burritts** [comment]
Yes, appears to be resolved by 0.14.1.  dnf install completed without error, and kopia appears to work.  I did very little testing, just ran the UI and kopia binary and verified the version was 0.14.1

**Comment by lupusA** [comment]
I will close it and the issue seems to be resolved. 

Cheers,

**Comment by jorgenman** [comment]
I'm still seeing this issue:
```
~ took 5s ❯ sudo dnf upgrade
Last metadata expiration check: 2:16:23 ago on Wed 27 Sep 2023 07:04:45 AM MDT.
Dependencies resolved.
=================================================================================================================================================================================
 Package                                Architecture                            Version                                             Repository                              Size
=================================================================================================================================================================================
Upgrading:
 slack                                  x86_64                                  4.34.120-0.1.el8                                    slack                                   83 M

Transaction Summary
=================================================================================================================================================================================
Upgrade  1 Package

Total size: 83 M
Is this ok [y/N]: y
Downloading Packages:
[SKIPPED] slack-4.34.120-0.1.el8.x86_64.rpm: Already downloaded                                                                                                                 
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  file /usr/lib/.build-id/3a/3ac62ceeacc1b5a5e83c8ba27b39aeb7d644dd from install of slack-4.34.120-0.1.el8.x86_64 conflicts with file from package kopia-ui-0.14.1-1.x86_64
```

It sounds like it may be the same issue as https://github.com/ferdium/ferdium-app/issues/416:
> To prevent this from conflicting with other Electron based apps, it's necessary to omit all the symlinks, to achieve this, Electron-builder uses fpm to have an easier way to build linux apps.
>
> The solution is to tell Electron-builder to have some flags on fpm while building the rpm to prevent creating those symlinks.
>
> According to Electron-builder documentation and fpm documentation this option is --rpm-rpmbuild-define "_build_id_links none", this should be changed on the electron-builder.yml file at the root of the project
>
> ...

**Comment by lupusA** [comment]
Reopen, as the issue still occurs.

**Comment by Sebastiaan76** [comment]
+1. I'm seeing this as well.

**Comment by samuelba** [comment]
Same issue here

```
Error: Transaction test error:
  file /usr/lib/.build-id/0c/2d8e22ef5f2efb220631be0f0689b3e660b2e9 from install of kopia-ui-0.19.0-1.x86_64 conflicts with file from package bitwarden-2025.1.3-1.x86_64
  file /usr/lib/.build-id/42/c5af8c6e4f2a07890083166687715c3a11b730 from install of kopia-ui-0.19.0-1.x86_64 conflicts with file from package bitwarden-2025.1.3-1.x86_64
  file /usr/lib/.build-id/67/c76173a2c42fd6e376bb9bbe31fe85809c7670 from install of kopia-ui-0.19.0-1.x86_64 conflicts with file from package bitwarden-2025.1.3-1.x86_64
  file /usr/lib/.build-id/8b/24d84e1544afb5350a55b885369ffe6264511a from install of kopia-ui-0.19.0-1.x86_64 conflicts with file from package bitwarden-2025.1.3-1.x86_64
  file /usr/lib/.build-id/a8/34d36162d41af409f7525201523af7c058c274 from install of kopia-ui-0.19.0-1.x86_64 conflicts with file from package bitwarden-2025.1.3-1.x86_64
  file /usr/lib/.build-id/e3/48af15b8a6fcd2c4941da68ed6a01e8c5be38d from install of kopia-ui-0.19.0-1.x86_64 conflicts with file from package bitwarden-2025.1.3-1.x86_64
  file /usr/lib/.build-id/e6/ca2f68a1aea97b79f2271a9a4332d229c54d68 from install of kopia-ui-0.19.0-1.x86_64 conflicts with file from package bitwarden-2025.1.3-1.x86_64
  file /usr/lib/.build-id/ed/cd57e4988dd2f47be67202a074edb4f1fa003d from install of kopia-ui-0.19.0-1.x86_64 conflicts with file from package bitwarden-2025.1.3-1.x86_64
```

is there any workaround to solve this?

**Comment by proborek** [comment]
Have exactly same issue as above. Any progress or solution?

**Comment by bbkz** [comment]
A additional build-id with the current stable/testing/unstable rpm:

```sh
Running transaction
Transaction failed: Rpm transaction failed.
  - file /usr/lib/.build-id/42/f633ec8d28e46e850ad58ffc5f831c734ab159 from install of kopia-ui-0.23.1-1.x86_64 conflicts with file from package slack-4.50.143-0.1.el8.x86_64
```

**Comment by bbkz** [comment]
Here is my workaround for others who need a working rpm:

```sh
TAG="v0.23.1" # as tagged in the github repo

mkdir /tmp/kopia
cd /tmp/kopia

cat <<EOF > build.sh
#!/bin/bash
dnf group install --refresh -y rpm-development-tools
dnf install -y git make golang libxcrypt-compat

git clone https://github.com/kopia/kopia.git
cd kopia
git checkout "$1"

make goreleaser
make kopia-ui

find . -name "*.x86_64.rpm" -exec mv {} /export \;
EOF
chmod 755 build.sh

podman run --rm -ti -v $(pwd):/export quay.io/fedora/fedora:44 /export/build.sh "$TAG"

ls /tmp/kopia
```
